CREATE TABLE songs(
  song_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  song_name varchar(100) DEFAULT 'no song title',
  album_name varchar(100) DEFAULT 'no album title',
  artist INTEGER REFERENCES artists(artist_id) NOT NULL
);